import = [
"~/.config/alacritty/themes/gruvbox_material.toml"
]

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
size = 12

[cursor]
style = { shape = "Block", blinking = "On" }
